language: ruby
rvm:
  - 2.2.3
notifications:
  slack: superldso:rcBWVLO1AxWgdF9sA19AoyCG
script:
  - bundle install
  - rake db:drop
  - rake db:migrate
  - rake sunspot:solr:start
  - rake sunspot:solr:reindex
  - rake db:seed
  - rake sunspot:solr:stop
