Ingredient.create!(name: "Esparguete", calories: 100)
Ingredient.create!(name: "Tomate", calories: 100)
Ingredient.create!(name: "Cebola", calories: 100)
Ingredient.create!(name: "Azeite", calories: 100)
Ingredient.create!(name: "Carne de vaca", calories: 100)
Ingredient.create!(name: "Alho", calories: 100)
Ingredient.create!(name: "Oregaos", calories: 100)
Ingredient.create!(name: "Pimenta preta", calories: 100)
Ingredient.create!(name: "Piri-piri", calories: 100)


Category.create!(name: "Almoco")
Category.create!(name: "Pequeno-Almoco")
Category.create!(name: "Jantar")
Category.create!(name: "Lanche")
