Ingredient.create!(name: "Spaghetti", unit: "g", calories: 1.58)
Ingredient.create!(name: "Tomato", unit: "g", calories: 0.18)
Ingredient.create!(name: "Onion", unit: "g", calories: 0.4)
Ingredient.create!(name: "Olive oil", unit: "ml", calories: 8.1)
Ingredient.create!(name: "Vegetable oil", unit: "ml", calories: 8.85)
Ingredient.create!(name: "Beef", unit: "g", calories: 2.88)
Ingredient.create!(name: "Garlic", unit: "g", calories: 1.49)
Ingredient.create!(name: "Oregano", unit: "g", calories: 2.65)
Ingredient.create!(name: "Black pepper", unit: "g", calories: 2.51)
Ingredient.create!(name: "Chili pepper", unit: "g", calories: 0.4)
Ingredient.create!(name: "Broccoli", unit: "g", calories: 0.34)
Ingredient.create!(name: "Red bell pepper", unit: "g", calories: 0.31)
Ingredient.create!(name: "Carrots", unit: "g", calories: 0.41)
Ingredient.create!(name: "Soy sauce", unit: "g", calories: 0.53)
Ingredient.create!(name: "Sesame seeds", unit: "g", calories: 5.73)
Ingredient.create!(name: "Corkscrew pasta", unit: "g", calories: 1.58)
Ingredient.create!(name: "Italian salad dressing", unit: "g", calories: 2.91)
Ingredient.create!(name: "Mayonnaise", unit: "g", calories: 6.8)
Ingredient.create!(name: "Chicken", unit: "g", calories: 2.39)
Ingredient.create!(name: "Bacon", unit: "g", calories: 5.41)
Ingredient.create!(name: "Muenster cheese", unit: "g", calories: 3.68)
Ingredient.create!(name: "Celery", unit: "g", calories: 0.16)
Ingredient.create!(name: "Green bell pepper", unit: "g", calories: 0.2)
Ingredient.create!(name: "Cherry tomato", unit: "g", calories: 0.23)
Ingredient.create!(name: "Avocado", unit: "g", calories: 0.16)
Ingredient.create!(name: "Penne pasta", unit: "g", calories: 3.52)
Ingredient.create!(name: "Hot italian sausage", unit: "g", calories: 1.96)
Ingredient.create!(name: "Chicken broth", unit: "g", calories: 0.85)
Ingredient.create!(name: "Basil", unit: "g", calories: 0.22)
Ingredient.create!(name: "Diced tomato", unit: "g", calories: 0.42)
Ingredient.create!(name: "Spinach", unit: "g", calories: 0.23)
Ingredient.create!(name: "Parmesan cheese", unit: "g", calories: 4.31)
Ingredient.create!(name: "Almonds", unit: "g", calories: 5.76)
Ingredient.create!(name: "Jalapeno pepper", unit: "g", calories: 0.28)
Ingredient.create!(name: "Ginger root", unit: "g", calories: 0.8)
Ingredient.create!(name: "Salt", unit: "g", calories: 0)
Ingredient.create!(name: "Lemon juice", unit: "g", calories: 0.22)
Ingredient.create!(name: "Heavy cream", unit: "g", calories: 3.45)
Ingredient.create!(name: "Butter", unit: "g", calories: 7.17)
Ingredient.create!(name: "Chickpeas", unit: "g", calories: 3.64)
Ingredient.create!(name: "Cucumber", unit: "g", calories: 0.16)
Ingredient.create!(name: "Black olives", unit: "g", calories: 1.15)
Ingredient.create!(name: "Red onion", unit: "g", calories: 0.4)
Ingredient.create!(name: "Feta cheese", unit: "g", calories: 2.64)
Ingredient.create!(name: "Garlic salt", unit: "g", calories: 0)
Ingredient.create!(name: "Cilantro salt", unit: "g", calories: 0)
Ingredient.create!(name: "Asparagus", unit: "g", calories: 0.2)
Ingredient.create!(name: "Rice", unit: "g", calories: 1.3)
Ingredient.create!(name: "Long grain rice", unit: "g", calories: 1.3)

Category.create!(name: "Breakfast")
Category.create!(name: "Lunch")
Category.create!(name: "Dinner")
