Ingredient.create!(name: "Esparguete", unit: "gm")
Ingredient.create!(name: "Tomate", unit: "pc")
Ingredient.create!(name: "Cebola", unit: "pc")
Ingredient.create!(name: "Azeite", unit: "cl")
Ingredient.create!(name: "Carne de vaca", unit: "gm")
Ingredient.create!(name: "Alho", unit: "pc")
Ingredient.create!(name: "Oregaos", unit: "gm")
Ingredient.create!(name: "Pimenta preta", unit: "gm")
Ingredient.create!(name: "Piri-piri", unit: "gm")


Category.create!(name: "Pequeno-Almoco")
Category.create!(name: "Almoco")
Category.create!(name: "Lanche")
Category.create!(name: "Jantar")
