# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

stepN = 1
$(document).ready ->
  $("#add_step").on "click", ->
    $('#add_step').before '<div class=\'col-md-12\' name=\'S[]\'><input required type=\'text\' class=\'step\' placeholder=\'Describe step ' + stepN + '\' name= \'S[]\' id= \'S' + stepN + '\'/></div>'
    stepN++
  $("#create").on "click", ->
    size=$('.step').length
    if size < 1
      alert('Please write a step')
      return false

  return


# ---
# generated by js2coffee 2.1.0
